// <auto-generated />
using APIMonstre.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIMonstre.Migrations
{
    [DbContext(typeof(MonstreContext))]
    [Migration("20250904131939_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("APIMonstre.Models.Monster", b =>
                {
                    b.Property<int>("IdMonster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMonster"));

                    b.Property<int>("DefenseBase")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceBase")
                        .HasColumnType("int");

                    b.Property<int>("ForceBase")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PointsVieBase")
                        .HasColumnType("int");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdMonster")
                        .HasName("PrimaryKey_MonsterId");

                    b.ToTable("Monster");
                });
#pragma warning restore 612, 618
        }
    }
}
