// <auto-generated />
using System;
using APIMonstre.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIMonstre.Migrations
{
    [DbContext(typeof(MonstreContext))]
    [Migration("20251216232205_classement")]
    partial class classement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("APIMonstre.Models.ChasseQuetes", b =>
                {
                    b.Property<int>("IdChasseQuetes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdChasseQuetes"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NbTue")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectifTue")
                        .HasColumnType("int");

                    b.Property<int>("PersonnageId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("XpRecompense")
                        .HasColumnType("int");

                    b.HasKey("IdChasseQuetes")
                        .HasName("PrimaryKey_ChasseQuetes");

                    b.HasIndex("PersonnageId");

                    b.ToTable("ChasseQuetes");
                });

            modelBuilder.Entity("APIMonstre.Models.HuntedMonster", b =>
                {
                    b.Property<int>("IdPersonnage")
                        .HasColumnType("int");

                    b.Property<int>("IdMonster")
                        .HasColumnType("int");

                    b.HasKey("IdPersonnage", "IdMonster");

                    b.HasIndex("IdMonster");

                    b.ToTable("HuntedMonster");
                });

            modelBuilder.Entity("APIMonstre.Models.InstanceMonstre", b =>
                {
                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<int>("MonstreId")
                        .HasColumnType("int");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<int>("PointsVieActuels")
                        .HasColumnType("int");

                    b.Property<int>("PointsVieMax")
                        .HasColumnType("int");

                    b.HasKey("PositionX", "PositionY");

                    b.HasIndex("MonstreId");

                    b.ToTable("InstanceMonstre");
                });

            modelBuilder.Entity("APIMonstre.Models.LevelUpQuetes", b =>
                {
                    b.Property<int>("IdLevelUpQuetes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLevelUpQuetes"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NiveauDepart")
                        .HasColumnType("int");

                    b.Property<int>("NiveauObjectif")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonnageId")
                        .HasColumnType("int");

                    b.Property<int>("XpRecompense")
                        .HasColumnType("int");

                    b.HasKey("IdLevelUpQuetes")
                        .HasName("PrimaryKey_LevelUpQuetes");

                    b.HasIndex("PersonnageId");

                    b.ToTable("LevelUpQuetes");
                });

            modelBuilder.Entity("APIMonstre.Models.Monster", b =>
                {
                    b.Property<int>("IdMonster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMonster"));

                    b.Property<int>("DefenseBase")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceBase")
                        .HasColumnType("int");

                    b.Property<int>("ForceBase")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PointsVieBase")
                        .HasColumnType("int");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type2")
                        .HasColumnType("longtext");

                    b.HasKey("IdMonster")
                        .HasName("PrimaryKey_MonsterId");

                    b.ToTable("Monster");
                });

            modelBuilder.Entity("APIMonstre.Models.Personnage", b =>
                {
                    b.Property<int>("IdPersonnage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPersonnage"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("DernierVillageX")
                        .HasColumnType("int");

                    b.Property<int>("DernierVillageY")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PiecesOr")
                        .HasColumnType("int");

                    b.Property<int>("PointsVie")
                        .HasColumnType("int");

                    b.Property<int>("PointsVieMax")
                        .HasColumnType("int");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.HasKey("IdPersonnage")
                        .HasName("PrimaryKey_PersonnageId");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Personnage");
                });

            modelBuilder.Entity("APIMonstre.Models.RandonneQuetes", b =>
                {
                    b.Property<int>("IdRandonneQuetes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRandonneQuetes"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonnageId")
                        .HasColumnType("int");

                    b.Property<int>("TuileX")
                        .HasColumnType("int");

                    b.Property<int>("TuileY")
                        .HasColumnType("int");

                    b.Property<int>("XpRecompense")
                        .HasColumnType("int");

                    b.HasKey("IdRandonneQuetes")
                        .HasName("PrimaryKey_RandonneQuetes");

                    b.HasIndex("PersonnageId");

                    b.HasIndex("TuileX", "TuileY");

                    b.ToTable("RandonneQuetes");
                });

            modelBuilder.Entity("APIMonstre.Models.Tuile", b =>
                {
                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<bool>("EstTraversable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("PositionX", "PositionY");

                    b.ToTable("Tuile");
                });

            modelBuilder.Entity("APIMonstre.Models.TypePositionHint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPersonnage")
                        .HasColumnType("int");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_TypePositionHint");

                    b.HasIndex("IdPersonnage");

                    b.ToTable("TypePositionHint");
                });

            modelBuilder.Entity("APIMonstre.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("estConnecte")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdUtilisateur")
                        .HasName("PrimaryKey_UtilisateurId");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("APIMonstre.Models.ChasseQuetes", b =>
                {
                    b.HasOne("APIMonstre.Models.Personnage", "Personnage")
                        .WithMany("ChasseQuetes")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnage");
                });

            modelBuilder.Entity("APIMonstre.Models.HuntedMonster", b =>
                {
                    b.HasOne("APIMonstre.Models.Monster", "Monster")
                        .WithMany("PersonnageTueurs")
                        .HasForeignKey("IdMonster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIMonstre.Models.Personnage", "Personnage")
                        .WithMany("HuntedMonster")
                        .HasForeignKey("IdPersonnage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("Personnage");
                });

            modelBuilder.Entity("APIMonstre.Models.InstanceMonstre", b =>
                {
                    b.HasOne("APIMonstre.Models.Monster", "Monstre")
                        .WithMany()
                        .HasForeignKey("MonstreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIMonstre.Models.Tuile", "Tuile")
                        .WithMany()
                        .HasForeignKey("PositionX", "PositionY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monstre");

                    b.Navigation("Tuile");
                });

            modelBuilder.Entity("APIMonstre.Models.LevelUpQuetes", b =>
                {
                    b.HasOne("APIMonstre.Models.Personnage", "Personnage")
                        .WithMany("LevelUpQuetes")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnage");
                });

            modelBuilder.Entity("APIMonstre.Models.Personnage", b =>
                {
                    b.HasOne("APIMonstre.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("APIMonstre.Models.RandonneQuetes", b =>
                {
                    b.HasOne("APIMonstre.Models.Personnage", "Personnage")
                        .WithMany("RandonneQuetes")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIMonstre.Models.Tuile", "Tuile")
                        .WithMany()
                        .HasForeignKey("TuileX", "TuileY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnage");

                    b.Navigation("Tuile");
                });

            modelBuilder.Entity("APIMonstre.Models.TypePositionHint", b =>
                {
                    b.HasOne("APIMonstre.Models.Personnage", "Personnage")
                        .WithMany("TypePositionHints")
                        .HasForeignKey("IdPersonnage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnage");
                });

            modelBuilder.Entity("APIMonstre.Models.Monster", b =>
                {
                    b.Navigation("PersonnageTueurs");
                });

            modelBuilder.Entity("APIMonstre.Models.Personnage", b =>
                {
                    b.Navigation("ChasseQuetes");

                    b.Navigation("HuntedMonster");

                    b.Navigation("LevelUpQuetes");

                    b.Navigation("RandonneQuetes");

                    b.Navigation("TypePositionHints");
                });
#pragma warning restore 612, 618
        }
    }
}
